id: "node1"
title: "Node 1"
description: "This is node 1"
version: "1.0.0"
tags:
  - "node"
  - "api"
  - "config"
  - "yaml"
  - "go"

deprecation:
  status: true
  at: "2024-03-15T00:00:00Z"
  reason: "Moving to new node 1 with enhanced security features"

schema:
  - name: "Prompt"
    type: "string"
    description: "The prompt for the app"
    default: "Hello, world!"
  - name: "Temperature"
    type: "number"
    description: "The temperature for the app"
    default: 0.5

