id: "node2"
title: "Node 2"
description: "This is node 2"
version: "2.0.0"
tags:
  - "node"
  - "api"
  - "config"
  - "yaml"
  - "go"
deprecation:
  status: false

schema:
  - name: "Prompt"
    type: "string"
    description: "The prompt for the app"
    default: "Hello, world!"
  - name: "Temperature"
    type: "number"
    description: "The temperature for the app"
